/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Book: typeof import('./src/components/Book.vue')['default']
    'Book.': typeof import('./src/components/Book..vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeLayout: typeof import('./src/components/HomeLayout.vue')['default']
    NewForm: typeof import('./src/components/NewForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
